import type { Metadata } from "next";
import Navbar from "./components/navbar";
import Sidebar from "./components/sidebar";

export const metadata: Metadata = {
  title: "NextNews App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <Navbar />
        <div className="flex">
          <Sidebar />
          <main className="flex-1 p-4">{children}</main>
        </div>
      </body>
    </html>
  );
}
